// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynvrbeavmuzlqlptcxpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludnJiZWF2bXV6bHFscHRjeHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDIxNzgsImV4cCI6MjA2MTA3ODE3OH0.aeA4j6MNyQGx3p-WezdsmyZ-mHNMCxzsMAlkNrAsrUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);